### ISSUE TITLE
comfortable-swipe : Command Not Found

### ISSUE THREAD

**Issue by Tak1za** [Hikari9/comfortable-swipe#2]
Even after installing everything successfully, it returns this error:
comfortable-swipe: command not found

**Comment by shane-evolve** [comment]
You have to add it to your path variable, or explicitly launch it from the install location. It requires superuser privileges to run, so if you want to run it at startup you could add it to your sudoers file to disable the password prompt and use the "sudo comfortable-swipe" command to launch.

**Comment by Tak1za** [comment]
I'm quite new to Ubuntu, would you mind guiding me through the process? Thank you
          
            
            On Oct 19 2017, at 3:19 am, shane-evolve <notifications@github.com> wrote:
            
            
              You have to add it to your path variable, or explicitly launch it from the install location. It requires superuser privileges to run, so if you want to run it at startup you could add it to your sudoers file to disable the password prompt and use the "sudo comfortable-swipe" command to launch.

**Comment by shane-evolve** [comment]
Sorry I don't think this is the best place. Forget about adding it to your path since it's not really important unless there are multiple users on the same computer that need the program. Search the web for environment variables to understand why you received the initial error.

Try using the command `locate comfortable-swipe`. This should lead you to the install location. Next time you run it, type that full path instead of just "comfortable-swipe".

I recommend this issue be closed.
