### ISSUE TITLE
Command on Gesture

### ISSUE THREAD

**Issue by MashalMohammed** [Hikari9/comfortable-swipe#67]
How can i run specific commands on certain gestures?

ex : down3 = notify-send "swipe 3 detected"
(is it already implemented? Does Xdotool allow it?)

btw, **Super work !** Best gesture tool ever ( tried touchegg, libinput-gestures,..etc )
Thank you so much

**Comment by Hikari9** [comment]
Thanks for your request. This sounds interesting, but it's kind of out-of-scope because we're triggering `xdotool` directly from C source code.

If you really wanna implement something depending on the gesture, the output of `comfortable-swipe start` can be used:

```bash
$> comfortable-swipe start
SWIPE down3
SWIPE left4
SWIPE left3
...
```

So if you want to run command on swipe, such as `notify-send`, you can have an `xargs` pipe which looks something like:

```bash
comfortable-swipe start | xargs -I{} notify-send "{} detected"
```

The following will be run every time a swipe is encountered:
```bash
notify-send "SWIPE down3 detected"
notify-send "SWIPE left4 detected"
notify-send "SWIPE left3 detected"
... 
```

You'll have to create a more advanced pipe if you want custom formatting.

And just be careful of having multiple comfortable-swipe programs running at the same time. Such feature for taking care of multiple programs will still be developed in the future.

Closing this issue for now. Hope that helps :)

**Comment by Hikari9** [comment]
As a post-note, if you want to run your extra pipe on startup, you'll have to edit the run script in the **autostart file** (usually, located in `~/.config/autostart/comfortable-swipe.desktop`)

**Comment by MashalMohammed** [comment]
So how do i run specific "script.sh" or commands like "shutdown" or any command i need
Please clarify if possible (if you don't mind, can you show the "shutdown" example)

Can this be a feature request?

And thank you so much.

**Comment by Hikari9** [comment]
If you want shutdown on `SWIPE down3` for example:
```
comfortable-swipe start | grep "SWIPE down3" --line-buffered | xargs -I{} shutdown now
```
